// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lomimruaagdsqbyrefwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbWltcnVhYWdkc3FieXJlZndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU3MjMsImV4cCI6MjA2NTUwMTcyM30.cWnoLKXuMsTlo7yGocrlwMYJhfm8tDXqYGAaFNHQNf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);